#!/bin/bash

CC="/opt/wasi-sdk/bin/clang -target wasm32-unknown-emscripten"
WASI_INC="-include /tmp/wasi-kit-hijack/include/etc.h -D__wasi__"
SHLIB_FLAGS="-nostdlib -Wl,--shared -Wl,--export-all -Wl,--import-table"


$CC -fPIC wasi-preconf/otherlibs/strstubs.c  -Iruntime $SHLIB_FLAGS -o dllcamlstr.wasm
$CC -fPIC wasi-preconf/otherlibs/unixstubs.c -Iruntime $SHLIB_FLAGS $WASI_INC -o dllunix.wasm
$CC -fPIC wasi-preconf/otherlibs/st_stubs.c  -Iruntime $SHLIB_FLAGS $WASI_INC -o dllthreads.wasm
